"""Tests for the literature query script."""

from __future__ import annotations

from io import StringIO
from pathlib import Path

import pytest
from ruamel.yaml import YAML

from literature.scripts.query import run

# ── Fixtures ───────────────────────────────────────────────────────────────────

PAPER_ALPHA = """\
---
abstract: "A novel approach using neural networks for sequence modelling."
authors:
- "Alpha, A."
citation_count: 100
cites: []
cited_by: []
doc_id: "alpha2020method"
doi: "10.0000/alpha"
et_al: false
reading_status:
  global: "unread"
related: []
resource_type: paper
tags:
- ml
- transformers
themes:
- deep-learning
title: "A Method for Neural Network Sequence Models"
tldr: "New neural architecture for sequences"
venue: "NeurIPS"
year: 2020
---

# Notes

Introduces a compact neural network approach.
Useful for downstream tasks.
"""

PAPER_BETA = """\
---
abstract: "We extend the BERT architecture with improved pretraining objectives."
authors:
- "Beta, B."
citation_count: 500
cites:
- id: "alpha2020method"
  type: "extends"
cited_by: []
doc_id: "beta2021bert"
doi: "10.0000/beta"
et_al: false
reading_status:
  global: "read"
related: []
resource_type: paper
tags:
- ml
- bert
themes:
- pretraining
title: "BERT Extensions and Beyond"
tldr: "Improves BERT pretraining"
venue: "ACL"
year: 2021
---

# Notes

Strong baseline for NLP benchmarks.
"""

PAPER_GAMMA = """\
---
abstract: "Diffusion models applied to generative tasks in high-dimensional spaces."
authors:
- "Gamma, G."
citation_count: 200
cites:
- id: "alpha2020method"
  type: "uses_method"
cited_by: []
doc_id: "gamma2022diffusion"
doi: "10.0000/gamma"
et_al: false
reading_status:
  global: "skimmed"
related: []
resource_type: paper
tags:
- diffusion
- generative
themes:
- generative-models
title: "Diffusion Models for Generation"
tldr: "Diffusion approach for generation"
venue: "ICML"
year: 2022
---

# Notes

Solid diffusion approach.
"""

GRAPH_YAML = """\
# Auto-generated by rebuild_index.py
nodes:
  alpha2020method:
    abstract: A novel approach using neural networks for sequence modelling.
    citation_count: 100
    resource_type: paper
    tags:
    - ml
    - transformers
    themes:
    - deep-learning
    title: A Method for Neural Network Sequence Models
    tldr: New neural architecture for sequences
    venue: NeurIPS
    year: 2020
  beta2021bert:
    abstract: We extend the BERT architecture with improved pretraining objectives.
    citation_count: 500
    resource_type: paper
    tags:
    - ml
    - bert
    themes:
    - pretraining
    title: BERT Extensions and Beyond
    tldr: Improves BERT pretraining
    venue: ACL
    year: 2021
  gamma2022diffusion:
    abstract: Diffusion models applied to generative tasks in high-dimensional spaces.
    citation_count: 200
    resource_type: paper
    tags:
    - diffusion
    - generative
    themes:
    - generative-models
    title: Diffusion Models for Generation
    tldr: Diffusion approach for generation
    venue: ICML
    year: 2022
edges:
- from: beta2021bert
  to: alpha2020method
  type: extends
- from: gamma2022diffusion
  to: alpha2020method
  type: uses_method
"""

STATUS_YAML = """\
# Auto-generated by rebuild_index.py
global:
  unread:
  - alpha2020method
  skimmed:
  - gamma2022diffusion
  read:
  - beta2021bert
  synthesized: []
"""


# ── Helpers ────────────────────────────────────────────────────────────────────


def _setup_literature_dir(tmp_path: Path) -> Path:
    """Create a minimal literature directory with 3 papers and pre-built index."""
    root = tmp_path / "literature"
    papers_dir = root / "papers"
    papers_dir.mkdir(parents=True)
    index_dir = root / "index"
    index_dir.mkdir()

    # Write paper files
    (papers_dir / "alpha2020method.md").write_text(PAPER_ALPHA, encoding="utf-8")
    (papers_dir / "beta2021bert.md").write_text(PAPER_BETA, encoding="utf-8")
    (papers_dir / "gamma2022diffusion.md").write_text(PAPER_GAMMA, encoding="utf-8")

    # Write pre-built index files
    (index_dir / "graph.yaml").write_text(GRAPH_YAML, encoding="utf-8")
    (index_dir / "status.yaml").write_text(STATUS_YAML, encoding="utf-8")

    return root


# ── search tests ───────────────────────────────────────────────────────────────


def test_search_matching_keyword(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Search for 'neural' returns alpha2020method which has it in title and abstract."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["search", "neural"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "alpha2020method" in captured.out
    assert "Neural Network" in captured.out


def test_search_tag_match(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Search for 'diffusion' matches gamma via its tag."""
    root = _setup_literature_dir(tmp_path)
    run(["search", "diffusion"], root=root)

    captured = capsys.readouterr()
    assert "gamma2022diffusion" in captured.out


def test_search_multiple_results(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Search for 'ml' tag returns both alpha and beta."""
    root = _setup_literature_dir(tmp_path)
    run(["search", "ml"], root=root)

    captured = capsys.readouterr()
    assert "alpha2020method" in captured.out
    assert "beta2021bert" in captured.out


def test_search_no_match(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Search for an absent keyword produces empty output."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["search", "xyzzy_nonexistent_token"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    assert captured.out.strip() == ""


def test_search_case_insensitive(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Search is case-insensitive: 'BERT' matches beta2021bert."""
    root = _setup_literature_dir(tmp_path)
    run(["search", "BERT"], root=root)

    captured = capsys.readouterr()
    assert "beta2021bert" in captured.out


def test_search_output_contains_year_and_status(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Search row includes year and reading status."""
    root = _setup_literature_dir(tmp_path)
    run(["search", "neural"], root=root)

    captured = capsys.readouterr()
    assert "2020" in captured.out
    assert "unread" in captured.out


# ── unread tests ───────────────────────────────────────────────────────────────


def test_unread_lists_unread_papers(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """unread subcommand returns only papers with global status unread."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["unread"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "alpha2020method" in captured.out
    # beta is read, gamma is skimmed — should not appear
    assert "beta2021bert" not in captured.out
    assert "gamma2022diffusion" not in captured.out


def test_unread_filter_by_matching_tag(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """unread --tags ml returns alpha (unread with ml tag)."""
    root = _setup_literature_dir(tmp_path)
    run(["unread", "--tags", "ml"], root=root)

    captured = capsys.readouterr()
    assert "alpha2020method" in captured.out


def test_unread_filter_by_non_matching_tag(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """unread --tags diffusion returns nothing (gamma is skimmed, not unread)."""
    root = _setup_literature_dir(tmp_path)
    run(["unread", "--tags", "diffusion"], root=root)

    captured = capsys.readouterr()
    assert captured.out.strip() == ""


def test_unread_filter_multiple_tags(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """unread --tags transformers,bert returns alpha (matches transformers)."""
    root = _setup_literature_dir(tmp_path)
    run(["unread", "--tags", "transformers,bert"], root=root)

    captured = capsys.readouterr()
    # alpha has 'transformers' tag and is unread
    assert "alpha2020method" in captured.out


def test_unread_filter_no_results(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """unread --tags nonexistent returns empty output."""
    root = _setup_literature_dir(tmp_path)
    run(["unread", "--tags", "nonexistent_tag"], root=root)

    captured = capsys.readouterr()
    assert captured.out.strip() == ""


# ── stats tests ────────────────────────────────────────────────────────────────


def test_stats_paper_count(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """stats output shows correct total paper count."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["stats"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Papers: 3" in captured.out


def test_stats_status_counts(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """stats output shows correct per-status counts."""
    root = _setup_literature_dir(tmp_path)
    run(["stats"], root=root)

    captured = capsys.readouterr()
    assert "unread: 1" in captured.out
    assert "skimmed: 1" in captured.out
    assert "read: 1" in captured.out
    assert "synthesized: 0" in captured.out


def test_stats_edge_count(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """stats output shows correct edge count."""
    root = _setup_literature_dir(tmp_path)
    run(["stats"], root=root)

    captured = capsys.readouterr()
    assert "Edges: 2" in captured.out


def test_stats_top_tags(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """stats output shows top tags section with correct tag counts."""
    root = _setup_literature_dir(tmp_path)
    run(["stats"], root=root)

    captured = capsys.readouterr()
    assert "Top tags:" in captured.out
    # 'ml' appears in alpha and beta → count 2
    assert "ml: 2" in captured.out


# ── paper tests ────────────────────────────────────────────────────────────────


def test_paper_valid_citekey(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """paper subcommand prints frontmatter for a valid citekey."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["paper", "alpha2020method"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    # Frontmatter fields
    assert "alpha2020method" in captured.out
    assert "A Method for Neural Network Sequence Models" in captured.out
    assert "2020" in captured.out


def test_paper_shows_body_preview(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """paper subcommand shows at least the first part of the body notes."""
    root = _setup_literature_dir(tmp_path)
    run(["paper", "alpha2020method"], root=root)

    captured = capsys.readouterr()
    # Body content from PAPER_ALPHA
    assert "neural network approach" in captured.out


def test_paper_invalid_citekey_exits_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """paper subcommand exits with code 1 and prints error for unknown citekey."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["paper", "nonexistent2099missing"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "nonexistent2099missing" in captured.err


# ── related tests ──────────────────────────────────────────────────────────────


def test_related_shows_both_directions(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """related for alpha shows beta (cited_by, extends) and gamma (cited_by, uses_method)."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["related", "alpha2020method"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0

    lines = captured.out.strip().splitlines()
    assert len(lines) == 2

    # Both beta and gamma cite alpha, so direction is cited_by
    assert any("cited_by" in l and "beta2021bert" in l for l in lines)
    assert any("cited_by" in l and "gamma2022diffusion" in l for l in lines)


def test_related_shows_edge_type(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """related output includes the edge type in parentheses."""
    root = _setup_literature_dir(tmp_path)
    run(["related", "alpha2020method"], root=root)

    captured = capsys.readouterr()
    assert "(extends)" in captured.out
    assert "(uses_method)" in captured.out


def test_related_outbound_edge(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """related for beta shows alpha as cites (outbound edge)."""
    root = _setup_literature_dir(tmp_path)
    run(["related", "beta2021bert"], root=root)

    captured = capsys.readouterr()
    lines = captured.out.strip().splitlines()
    assert len(lines) == 1
    assert "cites" in lines[0]
    assert "alpha2020method" in lines[0]


def test_related_invalid_citekey_exits_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """related exits with code 1 for an unknown citekey."""
    root = _setup_literature_dir(tmp_path)
    exit_code = run(["related", "nobody2099missing"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "nobody2099missing" in captured.err


def test_related_no_edges(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """related for a paper with no edges produces empty output."""
    # Add a 4th isolated paper to the index
    root = _setup_literature_dir(tmp_path)

    isolated_md = root / "papers" / "isolated2023alone.md"
    isolated_md.write_text(
        "---\ndoc_id: isolated2023alone\ntitle: Isolated Paper\nyear: 2023\n"
        "reading_status:\n  global: unread\nresource_type: paper\ntags: []\n---\n",
        encoding="utf-8",
    )

    # Patch graph.yaml to include the isolated node (no edges for it)
    y = YAML()
    graph_path = root / "index" / "graph.yaml"
    graph = y.load(graph_path.read_text(encoding="utf-8"))
    graph["nodes"]["isolated2023alone"] = {
        "title": "Isolated Paper",
        "year": 2023,
        "resource_type": "paper",
        "tags": [],
    }
    stream = __import__("io").StringIO()
    y.dump(graph, stream)
    graph_path.write_text(stream.getvalue(), encoding="utf-8")

    exit_code = run(["related", "isolated2023alone"], root=root)

    captured = capsys.readouterr()
    assert exit_code == 0
    assert captured.out.strip() == ""


# ── similar tests ──────────────────────────────────────────────────────────


def test_similar_returns_ranked_results(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """similar subcommand returns papers ranked by cosine similarity."""
    # Setup: create papers dir + embeddings.yaml
    papers_dir = tmp_path / "papers"
    papers_dir.mkdir()
    index_dir = tmp_path / "index"
    index_dir.mkdir()

    # Create query paper
    query_paper = papers_dir / "query_paper.md"
    query_paper.write_text(
        "---\ndoc_id: query_paper\ntitle: Query Paper\nyear: 2023\n"
        "reading_status:\n  global: unread\nresource_type: paper\ntags: []\n---\n",
        encoding="utf-8",
    )

    similar_paper = papers_dir / "similar_paper.md"
    similar_paper.write_text(
        "---\ndoc_id: similar_paper\ntitle: Similar Paper\nyear: 2023\n"
        "reading_status:\n  global: unread\nresource_type: paper\ntags: []\n---\n",
        encoding="utf-8",
    )

    dissimilar_paper = papers_dir / "dissimilar_paper.md"
    dissimilar_paper.write_text(
        "---\ndoc_id: dissimilar_paper\ntitle: Dissimilar Paper\nyear: 2023\n"
        "reading_status:\n  global: unread\nresource_type: paper\ntags: []\n---\n",
        encoding="utf-8",
    )

    # Create embeddings.yaml
    y = YAML()
    embeddings_data = {
        "model": "specter_v2",
        "dimensions": 3,
        "vectors": {
            "query_paper": [1.0, 0.0, 0.0],
            "similar_paper": [0.99, 0.1, 0.0],  # very similar
            "dissimilar_paper": [0.0, 0.0, 1.0],  # dissimilar
        },
    }
    with (index_dir / "embeddings.yaml").open("w") as f:
        y.dump(embeddings_data, f)

    exit_code = run(["similar", "query_paper", "--top", "1"], root=tmp_path)
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "similar_paper" in captured.out
    # dissimilar_paper should not appear (only top 1)
    assert "dissimilar_paper" not in captured.out


def test_similar_missing_embeddings_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """similar gives clear error when no embeddings.yaml exists."""
    # Create minimal structure
    (tmp_path / "papers").mkdir()
    (tmp_path / "index").mkdir()

    exit_code = run(["similar", "any_paper"], root=tmp_path)
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "rebuild_index" in captured.err


def test_similar_paper_not_in_embeddings(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """similar gives error when paper not in embeddings."""
    papers_dir = tmp_path / "papers"
    papers_dir.mkdir()
    index_dir = tmp_path / "index"
    index_dir.mkdir()

    y = YAML()
    with (index_dir / "embeddings.yaml").open("w") as f:
        y.dump(
            {
                "model": "specter_v2",
                "dimensions": 3,
                "vectors": {"other": [1.0, 0.0, 0.0]},
            },
            f,
        )

    exit_code = run(["similar", "missing_paper"], root=tmp_path)
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "not found" in captured.err
