"""
Rebuild literature index files (graph.yaml, status.yaml, references.bib, embeddings.yaml).

Scans all paper and resource markdown files in the literature directory,
reads their YAML frontmatter, and generates derived index files
for citation graphs, reading status tracking, BibTeX export, and
optionally SPECTER2 embeddings (when S2_API_KEY is set).

Usage:
    python literature/scripts/rebuild_index.py
    python literature/scripts/rebuild_index.py --root /path/to/literature/
    python literature/scripts/rebuild_index.py --skip-embeddings
"""

from __future__ import annotations

import argparse
import sys
from io import StringIO
from pathlib import Path


from ruamel.yaml import YAML

from literature.scripts.parse import read_frontmatter, write_paper_file
from literature.scripts.s2_client import SPECTER2_FIELD, S2Error, fetch_papers_batch

# ── Constants ──────────────────────────────────────────────────────────────────

NODE_FIELDS: tuple[str, ...] = (
    "abstract", "authors", "citation_count", "resource_type",
    "tags", "themes", "title", "tldr", "venue", "year",
)

STATUS_VALUES: tuple[str, ...] = ("read", "skimmed", "synthesized", "unread")

GRAPH_HEADER = (
    "# Auto-generated by rebuild_index.py \u2014 DO NOT EDIT\n"
    "# Regenerate: uv run python literature/scripts/rebuild_index.py\n"
)

STATUS_HEADER = "# Auto-generated by rebuild_index.py \u2014 DO NOT EDIT\n"

BIB_HEADER = "% Auto-generated by rebuild_index.py \u2014 DO NOT EDIT\n"


# ── YAML setup ─────────────────────────────────────────────────────────────────

def _make_yaml() -> YAML:
    """Create a YAML instance for deterministic output."""
    y = YAML()
    y.default_flow_style = False
    y.width = 4096
    return y


# ── Helpers ────────────────────────────────────────────────────────────────────

def _to_plain(value: object) -> object:
    """Recursively convert ruamel.yaml types to plain Python."""
    if isinstance(value, dict):
        return {str(k): _to_plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_plain(v) for v in value]
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return int(value)
    if isinstance(value, float):
        return float(value)
    if value is None:
        return None
    return str(value)


def _find_literature_root(start: Path | None = None) -> Path:
    """Search upward from *start* for a directory containing literature/AGENTS.md."""
    current = (start or Path.cwd()).resolve()
    for parent in [current, *current.parents]:
        candidate = parent / "literature" / "AGENTS.md"
        if candidate.is_file():
            return parent / "literature"
    return Path("./literature")


def _escape_bibtex(value: str) -> str:
    """Escape special characters for BibTeX field values."""
    return value.replace("&", "\\&").replace("%", "\\%")


def _write_yaml(data: dict, output: Path, header: str) -> None:
    """Write a dict as YAML with a header comment block."""
    y = _make_yaml()
    stream = StringIO()
    y.dump(data, stream)
    output.write_text(header + stream.getvalue(), encoding="utf-8")


# ── Scanning ───────────────────────────────────────────────────────────────────

def scan_documents(root: Path) -> dict[str, dict]:
    """Scan papers/ and resources/ for markdown files with frontmatter.

    Args:
        root: Path to the literature/ directory.

    Returns:
        Dict mapping citekeys to metadata dicts, sorted by citekey.
    """
    documents: dict[str, dict] = {}

    for subdir in ("papers", "resources"):
        dir_path = root / subdir
        if not dir_path.is_dir():
            continue
        for md_file in sorted(dir_path.glob("*.md")):
            if md_file.name == ".gitkeep":
                continue
            meta, _body = read_frontmatter(md_file)
            if not meta:
                print(
                    f"Warning: {md_file} has no frontmatter, skipping",
                    file=sys.stderr,
                )
                continue
            citekey = str(meta.get("doc_id", md_file.stem))
            documents[citekey] = meta

    return dict(sorted(documents.items()))


# ── Graph ──────────────────────────────────────────────────────────────────────

def build_graph(documents: dict[str, dict]) -> dict:
    """Build the citation graph data structure.

    Args:
        documents: Sorted dict of citekey -> metadata.

    Returns:
        Dict with ``nodes`` and ``edges`` keys.
    """
    nodes: dict[str, dict] = {}
    edges: list[dict[str, str]] = []

    for citekey in sorted(documents):
        meta = documents[citekey]

        # Extract node fields (alphabetical order, omit missing/None)
        node: dict = {}
        for field in NODE_FIELDS:
            if field in meta and meta[field] is not None:
                node[field] = _to_plain(meta[field])
        nodes[citekey] = node

        # Extract edges from cites list
        for cite_entry in (meta.get("cites") or []):
            if isinstance(cite_entry, dict):
                target = str(cite_entry.get("id", ""))
                rel_type = str(cite_entry.get("type", "cites"))
                if target:
                    edges.append({
                        "from": citekey,
                        "to": target,
                        "type": rel_type,
                    })

    edges.sort(key=lambda e: (e["from"], e["to"], e["type"]))

    return {"nodes": nodes, "edges": edges}


# ── Status ─────────────────────────────────────────────────────────────────────

def build_status(documents: dict[str, dict]) -> dict:
    """Build the reading status data structure.

    Args:
        documents: Sorted dict of citekey -> metadata.

    Returns:
        Dict with ``global`` and per-collaborator status sections.
    """
    # Collect all collaborator names
    collaborators: set[str] = set()
    for meta in documents.values():
        rs = meta.get("reading_status") or {}
        if isinstance(rs, dict):
            for key in rs:
                if key != "global":
                    collaborators.add(str(key))

    status_data: dict[str, dict[str, list[str]]] = {}

    # Global section
    global_buckets: dict[str, list[str]] = {s: [] for s in STATUS_VALUES}
    for citekey in sorted(documents):
        meta = documents[citekey]
        rs = meta.get("reading_status") or {}
        if isinstance(rs, dict):
            global_status = str(rs.get("global", "unread"))
        else:
            global_status = "unread"
        if global_status in global_buckets:
            global_buckets[global_status].append(citekey)
    status_data["global"] = global_buckets

    # Per-collaborator sections (sorted alphabetically)
    for collab in sorted(collaborators):
        buckets: dict[str, list[str]] = {s: [] for s in STATUS_VALUES}
        for citekey in sorted(documents):
            meta = documents[citekey]
            rs = meta.get("reading_status") or {}
            if not isinstance(rs, dict):
                status = "unread"
            else:
                collab_data = rs.get(collab)
                if collab_data is None:
                    status = "unread"
                elif isinstance(collab_data, dict):
                    status = str(collab_data.get("status", "unread"))
                else:
                    status = str(collab_data)
            if status in buckets:
                buckets[status].append(citekey)
        status_data[collab] = buckets

    return status_data


# ── BibTeX ─────────────────────────────────────────────────────────────────────

def format_bibtex(documents: dict[str, dict]) -> str:
    """Format all documents as a BibTeX string.

    Args:
        documents: Sorted dict of citekey -> metadata.

    Returns:
        Complete BibTeX file content as a string.
    """
    entries: list[str] = []

    for citekey in sorted(documents):
        meta = documents[citekey]
        resource_type = meta.get("resource_type", "")
        venue = meta.get("venue", "")
        entry_type = "article" if resource_type == "paper" and venue else "misc"

        # Build fields in alphabetical order
        fields: list[tuple[str, str]] = []

        abstract = meta.get("abstract")
        if abstract:
            fields.append(("abstract", _escape_bibtex(str(abstract))))

        authors = meta.get("authors", [])
        if authors:
            author_str = " and ".join(str(a) for a in authors)
            fields.append(("author", _escape_bibtex(author_str)))

        doi = meta.get("doi")
        if doi:
            fields.append(("doi", _escape_bibtex(str(doi))))

        if entry_type == "article" and venue:
            fields.append(("journal", _escape_bibtex(str(venue))))

        title = meta.get("title")
        if title:
            fields.append(("title", _escape_bibtex(str(title))))

        year = meta.get("year")
        if year is not None:
            fields.append(("year", str(year)))

        # Format entry
        lines = [f"@{entry_type}{{{citekey},"]
        for fname, fval in fields:
            lines.append(f"  {fname} = {{{fval}}},")
        lines.append("}")

        entries.append("\n".join(lines))

    if entries:
        return BIB_HEADER + "\n" + "\n\n\n".join(entries) + "\n"
    return BIB_HEADER


# ── cited_by backfill ──────────────────────────────────────────────────────────


def _backfill_cited_by(root: Path, graph: dict) -> None:
    """Write cited_by lists back into each paper's frontmatter.

    Builds the reverse-edge map from ``graph["edges"]`` and updates each paper
    file only when its ``cited_by`` field differs from the computed value.

    Args:
        root: Path to the ``literature/`` directory.
        graph: Citation graph dict as returned by :func:`build_graph`.
    """
    # Build reverse-edge map: target citekey -> list of {id, type} inbound edges
    cited_by_map: dict[str, list[dict[str, str]]] = {}

    # Ensure every known node has an entry (even if empty)
    for citekey in graph.get("nodes", {}):
        cited_by_map.setdefault(citekey, [])

    for edge in graph.get("edges", []):
        target = edge["to"]
        cited_by_map.setdefault(target, []).append(
            {"id": edge["from"], "type": edge["type"]}
        )

    for target in cited_by_map:
        cited_by_map[target].sort(key=lambda e: (e["id"], e["type"]))

    for subdir in ("papers", "resources"):
        dir_path = root / subdir
        if not dir_path.is_dir():
            continue
        for md_file in sorted(dir_path.glob("*.md")):
            if md_file.name == ".gitkeep":
                continue
            meta, body = read_frontmatter(md_file)
            if not meta:
                continue
            citekey = str(meta.get("doc_id", md_file.stem))
            new_cited_by = cited_by_map.get(citekey, [])
            old_cited_by = _to_plain(meta.get("cited_by") or [])
            if old_cited_by != new_cited_by:
                meta["cited_by"] = new_cited_by
                write_paper_file(md_file, meta, body)


# ── Embeddings ─────────────────────────────────────────────────────────────────


def _fetch_embeddings(
    documents: dict[str, dict],
    index_dir: Path,
    *,
    skip: bool = False,
) -> None:
    """Fetch SPECTER2 embeddings for papers with s2_id and write index/embeddings.yaml.

    Skipped silently if no S2_API_KEY env var is set, or if *skip* is True.
    Papers without ``s2_id`` are skipped silently.
    Papers where S2 returns a null embedding are skipped with a warning.

    Args:
        documents: Dict of ``{citekey: frontmatter_dict}`` for all papers.
        index_dir: The ``literature/index/`` directory to write embeddings.yaml to.
        skip: If True, skip embedding fetch entirely.
    """
    import os

    if skip:
        return
    api_key = os.environ.get("S2_API_KEY")
    if not api_key:
        return  # Silently skip — embeddings require API call

    # Collect s2_ids for papers that have them
    s2_id_to_citekey: dict[str, str] = {}
    for citekey, fm in documents.items():
        s2_id = fm.get("s2_id")
        if s2_id:
            s2_id_to_citekey[str(s2_id)] = citekey

    if not s2_id_to_citekey:
        return

    # Fetch SPECTER2 embeddings in one batch call
    paper_ids = list(s2_id_to_citekey.keys())
    try:
        batch_results = fetch_papers_batch(paper_ids, fields=SPECTER2_FIELD)
    except S2Error as exc:
        print(f"Warning: embedding fetch failed: {exc}", file=sys.stderr)
        return

    # Build vectors dict
    vectors: dict[str, list[float]] = {}
    for s2_id, result in zip(paper_ids, batch_results):
        if result is None:
            continue
        embedding_data = result.get("embedding") or {}
        vector = embedding_data.get("vector")
        if vector is None:
            citekey = s2_id_to_citekey[s2_id]
            print(f"Warning: no embedding for {citekey}", file=sys.stderr)
            continue
        citekey = s2_id_to_citekey[s2_id]
        # Round to 4 decimal places to reduce file size
        vectors[citekey] = [round(v, 4) for v in vector]

    if not vectors:
        return

    # Write embeddings.yaml
    yaml = _make_yaml()
    embeddings_data = {
        "model": "specter_v2",
        "dimensions": 768,
        "vectors": vectors,
    }
    embeddings_path = index_dir / "embeddings.yaml"
    with embeddings_path.open("w", encoding="utf-8") as fh:
        yaml.dump(embeddings_data, fh)
    print(f"Wrote {len(vectors)} embeddings to {embeddings_path}")


# ── Rebuild orchestration ──────────────────────────────────────────────────────

def rebuild(root: Path, *, skip_embeddings: bool = False) -> None:
    """Rebuild all index files under ``root/index/``.

    Args:
        root: Path to the ``literature/`` directory.
        skip_embeddings: If True, skip SPECTER2 embedding fetch.
    """
    documents = scan_documents(root)

    index_dir = root / "index"
    index_dir.mkdir(parents=True, exist_ok=True)

    # graph.yaml
    graph = build_graph(documents)
    _write_yaml(graph, index_dir / "graph.yaml", GRAPH_HEADER)

    # status.yaml
    status = build_status(documents)
    _write_yaml(status, index_dir / "status.yaml", STATUS_HEADER)

    # references.bib
    bib_content = format_bibtex(documents)
    (index_dir / "references.bib").write_text(bib_content, encoding="utf-8")

    _backfill_cited_by(root, graph)

    # SPECTER2 embeddings
    _fetch_embeddings(documents, index_dir, skip=skip_embeddings)

    print(f"Rebuilt index: {len(documents)} document(s)", file=sys.stderr)


# ── CLI ────────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    """Build the argparse parser for the rebuild_index CLI."""
    parser = argparse.ArgumentParser(
        description="Rebuild literature index files (graph.yaml, status.yaml, references.bib).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Path to literature/ directory (default: auto-detect)",
    )
    parser.add_argument(
        "--skip-embeddings",
        action="store_true",
        help="Skip SPECTER2 embedding fetch",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    """Entry point for the rebuild_index CLI."""
    parser = build_parser()
    args = parser.parse_args(argv)

    root = args.root or _find_literature_root()
    rebuild(root, skip_embeddings=args.skip_embeddings)


if __name__ == "__main__":
    main()
